version: '3'
services:
  app:
    build: ./docker/php
    container_name: skillup_php2
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.17
    container_name: skillup_nginx2
    ports:
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/skillup.local.conf:/etc/nginx/conf.d/skillup.local.conf
    depends_on:
      - app